Repository bit-ocean-studio/dolphin-admin-vue, pull requests merged in 2023-06, with the labels that each got.

#6 Feat: Signup & Login page
  components.d.ts
  src/api/index.ts
  src/api/login.ts
  src/api/signup.ts
  src/router/routes.ts
  src/types/index.ts
  src/types/request.ts
  src/types/user.ts
  src/views/Login/index.vue
  src/views/Signup/index.vue
Labels: Type: Feature, Infrastructure

#8 Refactor: Add auth layout
  src/Layouts/AuthLayout/index.vue
  src/Layouts/BaseLayout/index.vue
  src/router/routes.ts
  src/views/Login/index.vue
  src/views/Signup/index.vue
Labels: Type: Enhancement

#10 Fix: Axios request return 405 in prod env
  .env
  .env.example
  .eslintignore
  src/api/login.ts
  src/api/signup.ts
  src/api/upload.ts
  src/api/user.ts
  vercel.json
Labels: Type: Bug, Build Related, Infrastructure

#11 feat: animation
  src/layouts/AuthLayout/index.vue
  src/views/Login/index.vue
  src/views/Signup/index.vue
Labels: Type: Enhancement, Type: Style

#36 Refactor: Login & Signup form
  components.d.ts
  src/views/Login/index.vue
  src/views/Signup/index.vue
Labels: Type: Polish

#37 Feat: i18n
  README.zh-CN.md
  auto-imports.d.ts
  components.d.ts
  package.json
  pnpm-lock.yaml
  src/i18n/index.ts
  src/i18n/locales/en.json
  src/i18n/locales/zh-CN.json
  src/main.ts
  src/types/i18n.ts
  src/types/index.ts
  src/views/Home/index.vue
  tsconfig.json
  vite.config.ts
Labels: Type: Feature, Infrastructure

#38 Feat: i18n support
  .cspell/custom-words.txt
  components.d.ts
  src/api/axios/index.ts
  src/i18n/index.ts
  src/i18n/locales/en-US.json
  src/i18n/locales/en.json
  src/i18n/locales/zh-CN.json
  src/layouts/AuthLayout/index.vue
  src/store/theme.ts
  src/types/i18n.ts
  src/utils/index.ts
  src/utils/lang.ts
  src/views/Home/index.vue
  src/views/Login/index.vue
Labels: Type: Feature, Infrastructure

#39 Feat: Theme v1
  .cspell/custom-words.txt
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/api/axios/index.ts
  src/components.d.ts
  src/components/ThemeSwitchDevTool/index.vue
  src/components/index.ts
  src/constants/environments.ts
  src/constants/index.ts
  src/constants/theme.ts
  src/layouts/AuthLayout/index.vue
  src/store/theme.ts
  src/utils/index.ts
  src/utils/theme.ts
  src/views/Home/index.vue
  src/views/Login/index.vue
  src/views/Signup/index.vue
  tailwind.config.js
Labels: Type: Feature, Infrastructure

#42 Feat: i18n
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/views/Signup/index.vue
Labels: Type: Enhancement

#44 Feat: Base layout
  src/App.vue
  src/api/user.ts
  src/assets/base.scss
  src/components.d.ts
  src/components/BaseFooter/index.vue
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/index.vue
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/layouts/BaseLayout/index.vue
  src/main.ts
  src/router/routes.ts
  src/store/index.ts
  src/types/index.ts
  src/types/request.ts
  src/types/typeFc.ts
  src/types/user.ts
Labels: Type: Feature, Infrastructure

#47 Enhancement: Layout & header
  src/components.d.ts
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/index.vue
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/layouts/BaseLayout/index.vue
  src/store/index.ts
  src/store/sidebarStore.ts
Labels: Type: Enhancement

#50 Refactor: Vite config load from .env
  .env
  .env.example
  src/env.d.ts
  vite.config.ts
Labels: Build Related

#51 Build: Add cz-git & changelog
  .commitlintrc.js
  .commitlintrc.json
  CHANGELOG.md
  README.zh-CN.md
  package.json
  pnpm-lock.yaml
Labels: Type: DX

#53 feat(qrcode): :sparkles: add qrcode module
  .cspell/custom-words.txt
  docs/DEV_Standard.md
  package.json
  pnpm-lock.yaml
  src/app.config.ts
  src/components.d.ts
  src/components/BaseFooter/index.vue
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/index.vue
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/layouts/BaseLayout/index.vue
  src/router/index.ts
  src/router/routes.ts
  src/types/index.ts
  src/types/qrcode.ts
  src/types/siteMetaData.ts
  src/utils/index.ts
  src/utils/qrcode.ts
  src/views/Login/index.vue
  src/views/QRCode/index.vue
  src/views/Signup/index.vue
Labels: Type: Feature, Infrastructure

#60 Fix: Sidebar UI
  src/app.config.ts
  src/components/BaseSidebar/index.vue
  src/constants/menu.ts
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/store/sidebarStore.ts
  src/types/index.ts
  src/types/menu.ts
  src/utils/browser.ts
  src/utils/index.ts
  src/utils/render.ts
  src/views/QRCode/index.vue
Labels: Type: Enhancement, Type: Bug

#90 Fix: File path bug
  src/components.d.ts
  src/components/BaseHeader/index.vue
  src/constants/environments.ts
  src/constants/validation/user.ts
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/utils/file.ts
  src/views/Login/index.vue
  src/views/UserInfo/index.vue
Labels: Type: Bug

#91 perf: :zap: enchance user info
  src/components/BaseHeader/index.vue
  src/constants/index.ts
  src/constants/validation/index.ts
  src/constants/validation/user.ts
  src/views/Login/index.vue
  src/views/UserInfo/index.vue
Labels: Type: Enhancement, Type: Polish
