Repository bit-ocean-studio/dolphin-admin-vue, pull requests merged in 2023-08, with the labels that each got.

#274 Feat: Right click
  web/src/components/DRightClick/index.vue
  web/src/components/DRightClick/private/index.ts
  web/src/components/DRightClick/private/types.ts
  web/src/components/DRightClick/private/useContextMenu.ts
  web/src/constants/menu.ts
  web/src/locales/en_US.json
  web/src/locales/zh_CN.json
  web/src/router/routes.ts
  web/src/types/components.d.ts
  web/src/views/BuiltinComponents/Countdown/index.vue
  web/src/views/BuiltinComponents/RightClick/index.vue
Labels: Feature, Infrastructure

#276 Refactor: Migrate API to Nest.js
  .gitignore
  docs/package.json
  package.json
  pnpm-lock.yaml
  server/client/index.html
  server/nest-cli.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/config/index.ts
  server/src/decorators/swagger/api-paginated-response.ts
  server/src/main.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/auth/dto/create-auth.dto.ts
  server/src/modules/auth/dto/update-auth.dto.ts
  server/src/modules/auth/entities/auth.entity.ts
  server/src/modules/dictionaries/dictionaries.controller.ts
  server/src/modules/dictionaries/dictionaries.module.ts
  server/src/modules/dictionaries/dictionaries.service.ts
  server/src/modules/dictionaries/dto/create-dictionary.dto.ts
  server/src/modules/dictionaries/dto/update-dictionary.dto.ts
  server/src/modules/dictionaries/entities/dictionary.entity.ts
  server/src/modules/index.ts
  server/src/modules/upload/dto/file-upload-bulk.dto.ts
  server/src/modules/upload/dto/file-upload.dto.ts
  server/src/modules/upload/dto/index.ts
  server/src/modules/upload/upload.controller.ts
  server/src/modules/upload/upload.module.ts
  server/src/modules/upload/upload.service.ts
  server/src/modules/user-traffics/dto/create-user-traffic.dto.ts
  server/src/modules/user-traffics/dto/update-user-traffic.dto.ts
  server/src/modules/user-traffics/entities/user-traffic.entity.ts
  server/src/modules/user-traffics/user-traffics.controller.ts
  server/src/modules/user-traffics/user-traffics.module.ts
  server/src/modules/user-traffics/user-traffics.service.ts
  server/src/modules/users/dto/create-user.dto.ts
  server/src/modules/users/dto/index.ts
  server/src/modules/users/dto/update-user.dto.ts
  server/src/modules/users/dto/user.dto.ts
  server/src/modules/users/entities/index.ts
  server/src/modules/users/entities/user.entity.ts
  server/src/modules/users/users.controller.ts
  server/src/modules/users/users.module.ts
  server/src/modules/users/users.service.ts
  server/src/modules/websocket/dto/create-websocket.dto.ts
  server/src/modules/websocket/dto/update-websocket.dto.ts
  server/src/modules/websocket/entities/websocket.entity.ts
  server/src/modules/websocket/websocket.gateway.ts
  server/src/modules/websocket/websocket.module.ts
  server/src/modules/websocket/websocket.service.ts
  server/src/shared/dto/base-response.dto.ts
  server/src/shared/dto/index.ts
  server/src/shared/dto/paginated.dto.ts
  server/src/shared/index.ts
  server/tsconfig.json
  web/package.json
Labels: Breaking Change, Feature, Infrastructure, RESTful API, Migrate To Nest.js

#277 Build: :package: Deploy with GitHub Actions and pm2
  .github/workflows/deploy.yml
  package.json
  pnpm-lock.yaml
  server/src/main.ts
Labels: Feature, Build Related, Infrastructure, Config Related, CI/CD, Migrate To Nest.js

#281 Refactor: :recycle: Use d3 geoOrthographic to build world map
  pnpm-lock.yaml
  server/package.json
  web/.env.example
  web/package.json
  web/src/constants/environments.ts
  web/src/types/auto-imports.d.ts
  web/src/types/env.d.ts
  web/src/views/WebsiteAnalytics/TrafficStatistics/index.vue
  web/src/views/WebsiteAnalytics/TrafficStatistics/mock/countries.json
  web/src/views/WebsiteAnalytics/TrafficStatistics/mock/countrymesh.json
  web/src/views/WebsiteAnalytics/TrafficStatistics/mock/index.ts
  web/vite.config.ts
Labels: Bug, Polish, Refactor

#283 Refactor: Nest.js file storage
  .gitignore
  package.json
  pnpm-lock.yaml
  server/.env.example
  server/ecosystem.config.js
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/src/modules/upload/constants/index.ts
  server/src/modules/upload/constants/storage-config.ts
  server/src/modules/upload/dto/file-upload-bulk.dto.ts
  server/src/modules/upload/dto/file-upload.dto.ts
  server/src/modules/upload/dto/file.dto.ts
  server/src/modules/upload/dto/index.ts
  server/src/modules/upload/enum/index.ts
  server/src/modules/upload/upload.controller.ts
  server/src/modules/upload/upload.module.ts
  server/src/modules/upload/upload.service.ts
  server/src/modules/upload/validators/file-image-type.validator.ts
  server/src/modules/upload/validators/file-max-size.validator.ts
  server/src/modules/upload/validators/file-required.validator.ts
  server/src/modules/upload/validators/index.ts
  server/src/shared/dto/base-response.dto.ts
  server/src/shared/index.ts
  server/src/shared/storage.ts
  server/src/utils/index.ts
  server/src/utils/uuid.ts
  server/tsconfig.doc.json
  server/tsconfig.json
Labels: Feature, Infrastructure, Refactor

#286 Refactor: :recycle: Nest.js i18n
  .eslintignore
  .gitignore
  .lintstagedrc.json
  pnpm-lock.yaml
  server/nest-cli.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/common/dto/base-response.dto.ts
  server/src/common/dto/error-response.dto.ts
  server/src/common/dto/index.ts
  server/src/common/dto/page-response.dto.ts
  server/src/common/index.ts
  server/src/decorators/swagger/api-page-response.ts
  server/src/decorators/swagger/index.ts
  server/src/i18n/en_US/common.json
  server/src/i18n/en_US/home.json
  server/src/i18n/en_US/upload.json
  server/src/i18n/zh_CN/common.json
  server/src/i18n/zh_CN/home.json
  server/src/i18n/zh_CN/upload.json
  server/src/main.ts
  server/src/modules/home/home.controller.ts
  server/src/modules/home/home.module.ts
  server/src/modules/home/home.service.ts
  server/src/modules/index.ts
  server/src/modules/upload/upload.controller.ts
  server/src/modules/users/users.controller.ts
  server/src/shared/dto/index.ts
  server/src/shared/index.ts
Labels: Feature, Infrastructure, Refactor, i18n

#289 Refactor: Back-end bootstrap animation and log
  package.json
  pnpm-lock.yaml
  server/package.json
  server/src/app.config.ts
  server/src/main.ts
  server/src/types/index.ts
  server/src/types/site-metadata.ts
  server/src/types/time.ts
  server/src/utils/index.ts
  server/src/utils/logger.ts
  server/src/utils/time.ts
Labels: Feature, Infrastructure, Refactor

#291 Feat: :sparkles: Nest.js Logger
  pnpm-lock.yaml
  server/package.json
  server/src/app.module.ts
  server/src/common/dto/base-boolean-response.dto.ts
  server/src/common/dto/base-string-response.dto.ts
  server/src/common/index.ts
  server/src/common/map/file-extension.map.ts
  server/src/common/map/index.ts
  server/src/custom.logger.ts
  server/src/main.ts
  server/src/middlewares/api-logger.middleware.ts
  server/src/middlewares/index.ts
  server/src/modules/home/home.controller.ts
  server/src/modules/home/home.interface.ts
  server/src/modules/home/home.module.ts
  server/src/modules/home/home.service.ts
  server/src/modules/upload/dto/file.dto.ts
  server/src/modules/upload/upload.controller.ts
  server/src/modules/upload/upload.interface.ts
  server/src/modules/upload/upload.module.ts
  server/src/modules/upload/upload.service.ts
  server/src/shared/index.ts
  server/src/utils/index.ts
  server/src/utils/logger.ts
  server/src/utils/type.ts
  server/tsconfig.json
Labels: Feature, Infrastructure
