Repository bit-ocean-studio/dolphin-admin-vue, pull requests merged in 2023-07, with the labels that each got.

#93 Feat: :sparkles: Icon management
  .cspell/custom-words.txt
  .env
  package.json
  pnpm-lock.yaml
  src/App.vue
  src/api/axios/index.ts
  src/api/icon.ts
  src/api/index.ts
  src/api/login.ts
  src/api/signup.ts
  src/api/upload.ts
  src/api/user.ts
  src/components.d.ts
  src/components/BaseSidebar/model/index.ts
  src/constants/environments.ts
  src/constants/icon.ts
  src/constants/index.ts
  src/constants/theme.ts
  src/env.d.ts
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/router/routes.ts
  src/types/icon.ts
  src/types/index.ts
  src/types/request.ts
  src/utils/icon.ts
  src/utils/index.ts
  src/views/IconManagement/index.vue
  vite.config.ts
Labels: Type: Feature, Infrastructure

#97 Feat: User management
  src/api/user.ts
  src/components.d.ts
  src/components/BaseSidebar/model/index.ts
  src/constants/page.ts
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/router/routes.ts
  src/types/request.ts
  src/types/user.ts
  src/utils/time.ts
  src/views/UserManagement/index.vue
Labels: Type: Feature, Infrastructure

#98 Feat: :sparkles: Add router change transition
  src/components.d.ts
  src/layouts/BaseLayout/index.vue
Labels: Type: Enhancement, Type: UI

#102 Feat: :sparkles: Sidebar support collapse
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/index.vue
  src/components/BaseSidebar/model/index.ts
  src/components/BaseSidebar/models/index.ts
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/layouts/BaseLayout/index.vue
  src/store/sidebar.ts
  src/utils/index.ts
  src/utils/render.ts
Labels: Type: Feature, Type: UI

#107 Refactor: Auto imports
  src/App.vue
  src/api/axios/index.ts
  src/api/icon.ts
  src/api/index.ts
  src/api/login.ts
  src/api/signup.ts
  src/api/upload.ts
  src/api/user.ts
  src/auto-imports.d.ts
  src/components.d.ts
  src/components/AuthProvider/index.vue
  src/components/BaseFooter/index.vue
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/index.vue
  src/components/BaseSidebar/models/index.ts
  src/components/FileUploader/index.vue
  src/components/ThemeSwitchDevTool/index.vue
  src/i18n/index.ts
  src/layouts/AuthLayout/index.vue
  src/layouts/BaseLayout/index.vue
  src/layouts/DataTableLayout/index.vue
  src/main.ts
  src/pinia.ts
  src/router/dynamicRoutes.ts
  src/router/index.ts
  src/router/routes.ts
  src/store/index.ts
  src/store/theme.ts
  src/tools/faviconLoader.ts
  src/utils/auth.ts
  src/utils/authentication.ts
  src/utils/browser.ts
  src/utils/file.ts
  src/utils/icon.ts
  src/utils/index.ts
  src/utils/lang.ts
  src/utils/qrcode.ts
  src/utils/theme.ts
  src/utils/time.ts
  src/views/Home/index.vue
  src/views/IconManagement/index.vue
  src/views/Login/index.vue
  src/views/PermissionManagement/index.vue
  src/views/QRCode/index.vue
  src/views/RoleManagement/index.vue
  src/views/Signup/index.vue
  src/views/UserInfo/index.vue
  src/views/UserManagement/components/UserFormModal/index.vue
  src/views/UserManagement/index.vue
  vite.config.ts
Labels: Type: DX

#108 Fix: User management module i18n key bug
  docs/DEV_Standard.md
  src/api/axios/index.ts
  src/app.config.ts
  src/assets/images/bit_ocean.png
  src/components.d.ts
  src/components/BaseFooter/index.vue
  src/components/BaseSidebar/index.vue
  src/components/BaseSidebar/models/index.ts
  src/types/siteMetaData.ts
  src/views/UserManagement/components/UserFormModal/index.vue
  src/views/UserManagement/index.vue
Labels: Type: Bug, Type: i18n

#116 Feat: GitHub Icon
  src/api/user.ts
  src/app.config.ts
  src/auto-imports.d.ts
  src/components.d.ts
  src/components/BaseHeader/index.vue
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/layouts/DataTableLayout/index.vue
  src/types/siteMetaData.ts
  src/types/user.ts
  src/views/PermissionManagement/index.vue
  src/views/RoleManagement/index.vue
  src/views/UserInfo/index.vue
  src/views/UserManagement/components/UserFormModal/index.vue
  src/views/UserManagement/index.vue
  vite.config.ts
Labels: Type: Feature

#118 Fix: Bug
  src/components.d.ts
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/models/index.ts
  src/components/DolphinModalDialog/index.vue
  src/components/DolphinThemeSwitchDevTool/index.vue
  src/i18n/locales/en_US.json
  src/i18n/locales/zh_CN.json
  src/layouts/AuthLayout/index.vue
  src/layouts/DataTableLayout/index.vue
  src/router/routes.ts
  src/utils/auth.ts
  src/views/ChangePassword/index.vue
  src/views/ComponentsPreview/index.vue
  src/views/Login/index.vue
  src/views/UserManagement/components/UserFormModal/index.vue
  src/views/UserManagement/index.vue
Labels: Type: Bug

#119 Fix: :bug: Tooltip outline display error
  docs/DEV_Standard.md
  src/components/BaseHeader/index.vue
Labels: Type: Bug, Type: Style

#123 Fix: Fallback image
  src/layouts/AuthLayout/index.vue
  src/views/Home/index.vue
  src/views/NotFound/index.vue
  src/views/QRCode/index.vue
  src/views/UserInfo/index.vue
Labels: Type: Enhancement, Type: Bug, Type: Polish, Type: Style

#122 Refactor: Code structure
  docs/DEV_Standard.md
  index.html
  package.json
  pnpm-lock.yaml
  scripts/cspell-sort.js
  src/api/axios/config.ts
  src/api/axios/index.ts
  src/api/axios/statusCode.ts
  src/api/icon/index.ts
  src/api/icon/type.ts
  src/api/index.ts
  src/api/login.ts
  src/api/signup.ts
  src/api/upload/index.ts
  src/api/upload/type.ts
  src/api/user/index.ts
  src/api/user/type.ts
  src/app.config.ts
  src/auto-imports.d.ts
  src/components/AuthProvider/index.vue
  src/constants/environments.ts
  src/constants/page.ts
  src/constants/theme.ts
  src/env.d.ts
  src/hooks/useLoading/index.ts
  src/hooks/useLoading/type.ts
  src/layouts/AuthLayout/index.vue
  src/main.ts
  src/router/index.ts
  src/store/sidebar/index.ts
  src/store/theme/index.ts
  src/store/user/index.ts
  src/tools/faviconLoader/index.ts
  src/tools/naiveUILoader/index.ts
  src/types/file.ts
  src/types/index.ts
  src/types/menu.ts
  src/types/qrcode.ts
  src/types/request.ts
  src/types/theme.ts
  src/types/user.ts
  src/utils/auth.ts
  src/utils/browser.ts
  src/utils/file.ts
  src/utils/icon.ts
  src/utils/lang.ts
  src/utils/qrcode.ts
  src/utils/theme.ts
  src/utils/time.ts
  src/views/Login/index.vue
  src/views/Signup/index.vue
Labels: Type: Documentation, Breaking Change, Type: Refactor

#124 fix: :bug: fallback image
  src/components.d.ts
  src/views/UserInfo/index.vue
  src/views/UserManagement/components/UserFormModal/index.vue
Labels: Type: Bug

#130 Feat: Base tag
  .cspell/custom-words.txt
  src/auto-imports.d.ts
  src/components.d.ts
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/index.vue
  src/components/BaseSidebar/models/index.ts
  src/components/BaseTab/index.vue
  src/layouts/BaseLayout/index.vue
  src/layouts/DataTableLayout/index.vue
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/main.ts
  src/router/index.ts
  src/router/routes.ts
  src/store/index.ts
  src/store/tag/index.ts
  src/types/index.ts
  src/types/tag.ts
  src/utils/browser.ts
  src/views/ChangePassword/index.vue
Labels: Type: Feature, Infrastructure

#138 Fix: User management
  README.zh-CN.md
  docs/DEV_Standard.md
  index.html
  src/assets/base.scss
  src/assets/main.scss
  src/auto-imports.d.ts
  src/components.d.ts
  src/components/BaseFooter/index.vue
  src/components/BaseHeader/index.vue
  src/components/BaseHeader/private/constants.ts
  src/components/BaseHeader/private/index.ts
  src/components/BaseHeader/private/types.ts
  src/components/BaseSidebar/index.vue
  src/components/BaseSidebar/private/index.ts
  src/components/BaseSidebar/private/menu.ts
  src/components/BaseTab/index.vue
  src/components/BaseTabs/index.vue
  src/components/BaseTabs/private/index.ts
  src/components/BaseTabs/private/types.ts
  src/layouts/BaseLayout/index.vue
  src/layouts/DataTableLayout/index.vue
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/main.ts
  src/router/index.ts
  src/router/routes.ts
  src/store/index.ts
  src/store/tab/index.ts
  src/store/tag/index.ts
  src/types/index.ts
  src/types/tab.ts
  src/utils/auth/index.ts
  src/utils/browser.ts
  src/utils/browser/index.ts
  src/utils/browser/private/index.ts
  src/utils/browser/private/types.ts
  src/utils/file/index.ts
  src/utils/icon/index.ts
  src/utils/lang/index.ts
  src/utils/qrcode/index.ts
  src/utils/theme/index.ts
  src/utils/time/index.ts
  src/views/PermissionManagement/index.vue
  src/views/RoleManagement/index.vue
  src/views/UserManagement/components/UserFormModal/index.vue
  src/views/UserManagement/index.vue
  src/views/UserManagement/private/constants.ts
  src/views/UserManagement/private/index.ts
  vite.config.ts
Labels: Type: Bug, Type: Feature, Type: Refactor

#139 Feat: Clipboard
  src/components.d.ts
  src/components/BaseSidebar/private/menu.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/routes.ts
  src/views/Clipboard/index.vue
Labels: Type: Feature, Infrastructure

#141 Feat: Digital animation
  src/components.d.ts
  src/components/BaseSidebar/private/menu.ts
  src/components/NumberAnimation/index.vue
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/routes.ts
  src/views/Clipboard/index.vue
  src/views/DigitalAnimation/index.vue
  src/views/Home/index.vue
Labels: Type: Feature, Component Related, Infrastructure

#143 Feat: GitHub OAuth2
  .env
  .env.example
  src/api/auth/index.ts
  src/api/auth/types.ts
  src/api/axios/index.ts
  src/api/icon/index.ts
  src/api/icon/types.ts
  src/api/index.ts
  src/api/upload/index.ts
  src/api/upload/types.ts
  src/api/user/index.ts
  src/api/user/types.ts
  src/auto-imports.d.ts
  src/components.d.ts
  src/components/AuthProvider/index.vue
  src/components/BaseHeader/index.vue
  src/constants/environments.ts
  src/env.d.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/utils/auth/index.ts
  src/utils/github/index.ts
  src/utils/index.ts
  src/views/ChangePassword/index.vue
  src/views/Clipboard/index.vue
  src/views/Clipboard/private/constants.ts
  src/views/Clipboard/private/index.ts
  src/views/DigitalAnimation/index.vue
  src/views/Login/index.vue
  src/views/Login/private/index.ts
  src/views/Login/private/types.ts
  src/views/Signup/index.vue
Labels: Type: Feature, Infrastructure

#147 Feat: Bar chart
  .cspell/custom-words.txt
  README.md
  README.zh-CN.md
  package.json
  pnpm-lock.yaml
  src/charts/BarChart/index.vue
  src/charts/index.ts
  src/components.d.ts
  src/components/BaseSidebar/private/menu.ts
  src/components/ThemeSwitchDevTool/index.vue
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/routes.ts
  src/utils/github/index.ts
  src/views/ComponentsPreview/index.vue
  src/views/Echarts/index.vue
  src/views/Echarts/private/index.ts
  src/views/Echarts/private/mock.ts
  src/views/Home/index.vue
  src/views/Login/components/GitHubButton/index.vue
  src/views/Login/components/index.ts
  src/views/Login/index.vue
  vite.config.ts
Labels: Type: Feature, Component Related, Infrastructure

#151 Enhancement: Add user avatar
  src/auto-imports.d.ts
  src/views/UserInfo/index.vue
  src/views/UserManagement/components/UserFormModal/index.vue
  src/views/UserManagement/index.vue
  vite.config.ts
Labels: Type: Enhancement, Type: Style

#159 Feat: Total
  src/components.d.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/views/UserManagement/index.vue
Labels: Type: Enhancement

#160 Fix: Avatar upload bug
  src/components.d.ts
  src/views/UserInfo/index.vue
  src/views/UserManagement/components/UserFormModal/index.vue
  src/views/UserManagement/index.vue
Labels: Type: Bug

#165 Feat: WebSocket page
  .cspell/custom-words.txt
  package.json
  pnpm-lock.yaml
  src/components/BaseSidebar/private/menu.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/routes.ts
  src/views/UserManagement/components/UserFormModal/index.vue
  src/views/WebSocket/index.vue
  vite.config.ts
Labels: Type: Feature, Infrastructure

#166 Feat: Excel
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/auto-imports.d.ts
  src/components/BaseSidebar/private/menu.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/routes.ts
  src/types/excel.ts
  src/types/index.ts
  src/utils/excel/index.ts
  src/utils/index.ts
  src/views/Excel/index.vue
  src/views/Excel/private/constants.ts
  src/views/Excel/private/index.ts
Labels: Type: Feature, Infrastructure

#167 Feat: Print
  src/components/BaseSidebar/private/menu.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/routes.ts
  src/views/Print/index.vue
Labels: Type: Feature, Infrastructure

#168 Feat: Error page
  src/assets/images/403.png
  src/assets/images/404.png
  src/assets/images/500.png
  src/components/BaseSidebar/private/menu.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/routes.ts
  src/views/403/index.vue
  src/views/404/index.vue
  src/views/500/index.vue
Labels: Type: Feature, Infrastructure

#170 Social
  package.json
  pnpm-lock.yaml
  src/auto-imports.d.ts
  src/components/BaseHeader/index.vue
  src/components/BaseHeader/private/constants.ts
  src/components/BaseSidebar/index.vue
  src/components/BaseSidebar/private/menu.ts
  src/components/BaseSidebar/private/render.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/index.ts
  src/router/routes.ts
  src/types/i18n.ts
  src/types/index.ts
  src/types/menu.ts
  src/views/NotFound/index.vue
  vite.config.ts
Labels: Breaking Change, Type: Polish, :tada:

#172 Refactor: Views file structure
  .cspell/custom-words.txt
  src/assets/images/403.png
  src/assets/images/404.png
  src/assets/images/500.png
  src/components.d.ts
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/index.vue
  src/components/BaseSidebar/private/menu.ts
  src/components/BaseSidebar/private/render.ts
  src/layouts/DataTableLayout/index.vue
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/index.ts
  src/router/prefix.ts
  src/router/processor.ts
  src/router/router.d.ts
  src/router/routes.ts
  src/views/403/index.vue
  src/views/404/index.vue
  src/views/500/index.vue
  src/views/Auth/AuthRedirect/index.vue
  src/views/Auth/Login/components/GitHubLogin/index.vue
  src/views/Auth/Login/components/GoogleLogin/index.vue
  src/views/Auth/Login/components/index.ts
  src/views/Auth/Login/index.vue
  src/views/Auth/Login/private/index.ts
  src/views/Auth/Login/private/types.ts
  src/views/Auth/Signup/index.vue
  src/views/BuiltinComponents/DigitalAnimation/index.vue
  src/views/ErrorPages/403/index.vue
  src/views/ErrorPages/404/index.vue
  src/views/ErrorPages/418/index.vue
  src/views/ErrorPages/500/index.vue
  src/views/SystemFunctions/PermissionManagement/index.vue
  src/views/SystemFunctions/RoleManagement/index.vue
  src/views/SystemFunctions/UserManagement/components/UserFormModal/index.vue
  src/views/SystemFunctions/UserManagement/components/index.ts
  src/views/SystemFunctions/UserManagement/index.vue
  src/views/SystemTools/Clipboard/index.vue
  src/views/SystemTools/Clipboard/private/constants.ts
  src/views/SystemTools/Clipboard/private/index.ts
  src/views/SystemTools/Excel/index.vue
  src/views/SystemTools/Excel/private/constants.ts
  src/views/SystemTools/Excel/private/index.ts
  src/views/SystemTools/Icon/index.vue
  src/views/SystemTools/Print/index.vue
  src/views/SystemTools/QRCode/index.vue
  src/views/SystemTools/WebSocket/index.vue
  src/views/UniversalComponents/Charts/index.vue
  src/views/UniversalComponents/Charts/private/index.ts
  src/views/UniversalComponents/Charts/private/mock.ts
  src/views/User/ChangePassword/index.vue
  src/views/User/UserInfo/index.vue
  src/views/UserManagement/private/constants.ts
  src/views/UserManagement/private/index.ts
Labels: Type: Enhancement, Breaking Change, Type: Refactor

#174 Feat: Breadcrumb
  src/auto-imports.d.ts
  src/components.d.ts
  src/components/BaseBreadcrumb/index.vue
  src/components/BaseFooter/index.vue
  src/components/BaseHeader/index.vue
  src/components/BaseSidebar/index.vue
  src/components/BaseSidebar/private/index.ts
  src/components/BaseSidebar/private/render.ts
  src/constants/index.ts
  src/constants/menu.ts
  src/router/routes.ts
  src/utils/index.ts
  src/utils/render/index.ts
  vercel.json
  vite.config.ts
Labels: Type: Feature, Infrastructure

#175 Feat: User management add search text and date filter
  src/auto-imports.d.ts
  src/constants/page.ts
  src/layouts/DataTableLayout/index.vue
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/types/request.ts
  src/views/SystemFunctions/UserManagement/index.vue
  vite.config.ts
Labels: Type: Enhancement, Type: Feature, Infrastructure

#176 chore: update
  README.md
  README.zh-CN.md
  src/api/axios/index.ts
  src/api/axios/statusCode.ts
  src/api/user/index.ts
  src/views/SystemFunctions/UserManagement/index.vue
  src/views/SystemTools/Clipboard/index.vue
Labels: Type: Bug

#178 Feat: Print
  src/App.vue
  src/components.d.ts
  src/components/HTMLPrinter/index.vue
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/views/SystemTools/Print/index.vue
Labels: Type: Bug, Type: Polish

#179 Feat: User management add sort and filter
  .eslintrc.js
  src/App.vue
  src/api/user/index.ts
  src/components.d.ts
  src/components/AuthProvider/index.vue
  src/constants/page.ts
  src/layouts/BaseLayout/index.vue
  src/layouts/DataTableLayout/index.vue
  src/types/request.ts
  src/views/SystemFunctions/UserManagement/index.vue
  src/views/SystemFunctions/UserManagement/private/index.ts
  src/views/SystemFunctions/UserManagement/private/models.ts
  src/views/SystemFunctions/UserManagement/private/types.ts
Labels: Type: Feature, Infrastructure

#180 Feat: Timeline
  .cspell/custom-words.txt
  src/components.d.ts
  src/constants/menu.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/routes.ts
  src/utils/render/index.ts
  src/views/BuiltinComponents/Timeline/index.vue
  src/views/BuiltinComponents/Timeline/private/index.ts
  src/views/BuiltinComponents/Timeline/private/mock.ts
Labels: Type: Feature, Component Related, Infrastructure

#182 Fix: Timeline
  .cspell/custom-words.txt
  .husky/pre-commit
  src/components.d.ts
  src/components/Timeline/index.vue
  src/components/Timeline/private/index.ts
  src/components/Timeline/private/types.ts
  src/views/BuiltinComponents/Timeline/index.vue
  src/views/BuiltinComponents/Timeline/private/mock.ts
Labels: Type: Bug, Type: Polish

#183 Fix: Print bug
  .cspell/custom-words.txt
  src/App.vue
  src/auto-imports.d.ts
  src/components.d.ts
  src/components/HTMLPrinter/index.vue
  src/components/HTMLPrinter/private/index.ts
  src/components/HTMLPrinter/private/types.ts
  src/components/NumberAnimation/private/types.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/utils/render/index.ts
  src/views/SystemTools/Print/index.vue
  src/views/SystemTools/Print/private/index.ts
  src/views/SystemTools/Print/private/mock.ts
  src/views/SystemTools/Print/private/types.ts
  vite.config.ts
Labels: Type: Bug, Type: Polish

#185 Feat: Chatroom
  src/api/auth/index.ts
  src/api/axios/index.ts
  src/components.d.ts
  src/constants/menu.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/router/prefix.ts
  src/router/routes.ts
  src/views/SystemApplications/ChatChannels/components/ChannelList/index.vue
  src/views/SystemApplications/ChatChannels/components/ChatList/index.vue
  src/views/SystemApplications/ChatChannels/components/UserList/index.vue
  src/views/SystemApplications/ChatChannels/components/index.ts
  src/views/SystemApplications/ChatChannels/index.vue
  src/views/SystemApplications/ChatChannels/private/constants.ts
  src/views/SystemApplications/ChatChannels/private/index.ts
Labels: Type: Feature, Infrastructure

#203 Feat: :sparkles: Add system loading in AuthLayout
  src/layouts/AuthLayout/index.vue
Labels: Type: Enhancement

#195 Feat: Navigation page
  index.html
  src/auto-imports.d.ts
  src/components.d.ts
  src/constants/menu.ts
  src/locales/en_US.json
  src/locales/zh_CN.json
  src/utils/index.ts
  src/utils/navigation/index.ts
  src/views/Navigation/components/Search/index.vue
  src/views/Navigation/components/ShortcutItem/index.vue
  src/views/Navigation/components/index.ts
  src/views/Navigation/index.vue
Labels: Type: Feature, Infrastructure

#206 Feat: Navigation page support sort shortcuts
  src/views/Navigation/components/ShortcutItem/index.vue
  src/views/Navigation/index.vue
Labels: Type: Enhancement, Good First Issue

#207 Enhancement: Tabs dnd
  src/components.d.ts
  src/components/BaseTabs/index.vue
  src/views/Navigation/components/ShortcutItem/index.vue
  src/views/Navigation/index.vue
Labels: Type: Enhancement

#213 Feat: Monorepo
  .eslintignore
  .eslintrc.js
  .prettierignore
  README.md
  README.zh-CN.md
  package.json
  pnpm-lock.yaml
  tsconfig.json
  tsconfig.node.json
  tsconfig.web.json
  web/package.json
  web/src/api/axios/index.ts
  web/src/components.d.ts
  web/src/components/BaseFooter/index.vue
  web/src/components/BaseHeader/index.vue
  web/src/components/BaseSidebar/index.vue
  web/src/components/BaseTabs/index.vue
  web/src/components/ThemeSwitchDevTool/index.vue
  web/src/locales/en_US.json
  web/src/locales/zh_CN.json
  web/src/types/env.d.ts
  web/src/types/shims.d.ts
  web/src/views/Auth/Login/index.vue
  web/src/views/Auth/Signup/index.vue
  web/src/views/SystemApplications/ChatChannels/index.vue
  web/tsconfig.json
  web/vite.config.ts
Labels: Breaking Change, Type: Feature, Infrastructure, Type: Refactor, Dependencies

#220 Feat: Init docs site
  .eslintignore
  .gitignore
  .husky/pre-commit
  .prettierignore
  docs/.env.example
  docs/app.config.ts
  docs/app.vue
  docs/assets/global.scss
  docs/assets/images/bit_ocean.png
  docs/assets/images/favicon.png
  docs/composables/useAsset.ts
  docs/layouts/BaseLayout.vue
  docs/nuxt.config.ts
  docs/package.json
  docs/pages/index.vue
  docs/public/favicon.ico
  docs/server/tsconfig.json
  docs/tailwind.config.ts
  docs/tsconfig.json
  docs/types/index.ts
  package.json
  pnpm-lock.yaml
  server/package.json
  web/package.json
  web/src/app.config.ts
  web/src/components/BaseHeader/index.vue
  web/src/locales/en_US.json
  web/src/locales/zh_CN.json
  web/src/types/siteMetaData.ts
Labels: Type: Documentation

#254 Feat: Traffic statistics world map
  pnpm-lock.yaml
  web/package.json
  web/src/constants/menu.ts
  web/src/locales/en_US.json
  web/src/locales/zh_CN.json
  web/src/router/prefix.ts
  web/src/router/routes.ts
  web/src/views/WebsiteAnalytics/TrafficStatistics/index.vue
  web/src/views/WebsiteAnalytics/TrafficStatistics/private/countries.json
  web/src/views/WebsiteAnalytics/TrafficStatistics/private/countrymesh.json
  web/src/views/WebsiteAnalytics/TrafficStatistics/private/data.ts
  web/src/views/WebsiteAnalytics/TrafficStatistics/private/index.ts
Labels: Feature, Infrastructure, Web PC

#256 Fix: :bug: Page display error
  .eslintrc.js
  .husky/pre-commit
  docs/nuxt.config.ts
  docs/package.json
  pnpm-lock.yaml
  tsconfig.web.json
  web/src/App.vue
  web/src/components/BaseGlobalLoading/index.vue
  web/src/layouts/AuthLayout/index.vue
  web/src/layouts/BaseLayout/index.vue
  web/src/locales/zh_CN.json
  web/src/types/components.d.ts
  web/src/views/WebsiteAnalytics/TrafficStatistics/index.vue
  web/src/views/WebsiteAnalytics/TrafficStatistics/mock/countries.json
  web/src/views/WebsiteAnalytics/TrafficStatistics/mock/countrymesh.json
  web/src/views/WebsiteAnalytics/TrafficStatistics/mock/data.ts
  web/src/views/WebsiteAnalytics/TrafficStatistics/mock/index.ts
  web/src/views/WebsiteAnalytics/TrafficStatistics/private/index.ts
Labels: Bug, Web PC

#258 Feat: List template
  web/src/constants/menu.ts
  web/src/locales/en_US.json
  web/src/locales/zh_CN.json
  web/src/router/prefix.ts
  web/src/router/routes.ts
  web/src/views/CodeTemplates/ListTemplates/index.vue
  web/src/views/CodeTemplates/ListTemplates/private/index.ts
  web/src/views/CodeTemplates/ListTemplates/private/models.ts
  web/src/views/CodeTemplates/ListTemplates/private/types.ts
  web/src/views/SystemFunctions/UserManagement/index.vue
Labels: Feature, Infrastructure, Web Mobile, Web PC

#260 Feat: TSConfig
  .eslintrc.js
  docs/content/tech-stack/eslint.md
  docs/nuxt.config.ts
  package.json
  packages/eslint-config/package.json
  pnpm-lock.yaml
  server/package.json
  server/tsconfig.json
  tsconfig.base.json
  tsconfig.json
  tsconfig.node.json
  tsconfig.web.json
  web/package.json
  web/src/types/components.d.ts
Labels: DX, Refactor
